[package]
name = "gladiators"
version = "0.1.0"
edition = "2021"
default-run = "main"

[lib]
name = "characters_lib"
path = "src/characters_lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[dependencies]
bevy = "0.9.0"
log = "0.4.14"
